### ISSUE TITLE
Illegal instruction (core dumped) on Rust implementation

### ISSUE THREAD

**Issue by arthurmoises** [resin-io/resin-wifi-connect#111]
Hi! 

Today I cloned the rust implementation repo and pushed it to a raspberry pi zero w application on resin cloud. When it started and when i run ./resin_wifi-connection, I got this error: 

`Illegal instruction (core dumped) `

It's because it can't be run on ARMv6?

**Comment by josephroberts** [comment]
Hi,

Please use https://github.com/majorz/resin-wifi-connect for now. We will be merging the project into this repo at some point in the coming week.

**Comment by arthurmoises** [comment]
Hi @josephroberts 

I did that yesterday, I cloned that repo to my machine, and, without any modifications, pushed it to the resin cloud. After running the Rust executable, I got the above error: "Illegal instruction (core dumped)". 

But no rush. I will developing another parts of the application and at the same time, debugging with the serial tool as you advised.

**Comment by alexandrosm** [comment]
@josephroberts @majorz why is project code being kept in a personal
account? This is an anti-pattern we should avoid. Please bring the code
into the main repo asap. Cc @petrosagg

**Comment by majorz** [comment]
@arthurmoises, following up on this issue-- the newly released version of resin-wifi-connect v3.0.0 is now working on Raspberry Pi 1 and Zero / ARMv6. The error was because we used the debian toolchains for cross-compiling for ARMv6, instead of the raspbian fork, which produces proper ARMv6 hard-float binaries.
