### ISSUE TITLE
Deprecate version 2 in favor of the upcoming version 3

### ISSUE THREAD

**Issue by majorz** [resin-io/resin-wifi-connect#112]
Show a deprecation message during the install and when running in the dashboard logs.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2pkh)

**Comment by p0wl** [comment]
There is no tag for version 3, is it also from this repository?

**Comment by Johnsel** [comment]
Yes very confusing, where is v3?

**Comment by majorz** [comment]
Sorry for causing this confusion! I should have merged this PR just before the release of v3, which got delayed because of ARMv6 issues. Those are all fixed now and v3 is coming very shortly this week.

**Comment by Johnsel** [comment]
Oh ok, thanks. Would you recommend waiting for it/are there big code changes vs v2? I am planning a new deployment using ResinOS v2.x and need to integrate some of our own custom modifications in the resin-wifi-connect module, so it might be a waste of time if I have to do it all over again differently for v3.

**Comment by majorz** [comment]
Hi @Johnsel, the next version is a complete rewrite using the Rust programming language, so it may be challenging to transfer your customization to v3 and in that case I would recommend continue using v2 for now.

Currently v3 comes with the same feature set as v2, but has the advantages of much smaller Docker image sizes, faster image build and deployment times, smaller memory footprint and better cpu utilization.

In the upcoming versions we will continue to expand the functionality of v3 and we are looking forward to accommodate more use cases, e.g. static ip assignment, etc. We will continue to maintain v2 with bugfixes, after v3 is released, but we do not have plans for expanding it with new features.

Can you please share what type of modifications are you using on top of v2?

**Comment by majorz** [comment]
@p0wl @Johnsel pinging you just to let you know, that v3.0.0 of resin-wifi-connect is now available.
