### ISSUE TITLE
Clearing credentials only when not network connection could be established

### ISSUE THREAD

**Issue by p0wl** [resin-io/resin-wifi-connect#115]
Why is it not possible to configure resin-wifi-connect that way, that the credentials get only removed when a network connection could not be established.

Right now only two modes are possible:
 * `--clear=true` => always remove credentials, although they might be valid
 * `--clear=false` => never ask, although they might be invalid -> device will stay offline

I want to clear the credentials when the connection is not working. Is this not intended? Why?

Nonetheless, thanks for this awesome project! Setup was very easy and it works great! ❤️

**Comment by majorz** [comment]
Hi @p0wl, sorry for the delayed response! Thanks for the nice words 😄 

The `--clear` option is not that flexible at the moment and can be confusing indeed.

`--clear=false` is intended for scenarios where the defined Wi-Fi access point connections can be temporary unavailable, and it only attempts to connect, but does not start the hotspot for entering credentials for a new access point. We need to accommodate other different use cases like yours and I bring it up to the team once we release v3, which is coming very shortly.

**Comment by p0wl** [comment]
Thanks for the response! I monkey patched the functionality in v2 in my fork (see https://github.com/p0wl/resin-wifi-connect/commit/677182e39aea77e79495b8a19378dbac8fb90c38). When v3 is released, I'll have a look if I can contribute that functionality to the project.

**Comment by majorz** [comment]
@p0wl, closing this in favor of #145, which targets the same issue.
