### ISSUE TITLE
Raspbian Stretch install script

### ISSUE THREAD

**Issue by majorz** [resin-io/resin-wifi-connect#116]
Implement a bash script for easy installation on Raspbian Stretch. This requires downloading the upcoming v3 from Github releases, disabling dhcpcd and installing and activating NetworkManager.

**Comment by shawnipoo** [comment]
Running either install script fails. Is there a fresh install script? Thank you.

**Comment by lurch** [comment]
I guess this can be closed now?

**Comment by majorz** [comment]
Implemented in #117.
