### ISSUE TITLE
Error running Raspbian install script

### ISSUE THREAD

**Issue by andrewn** [resin-io/resin-wifi-connect#140]
I was just testing the script in #117 but came across an error.

I'm testing on the latest "2017-09-07-raspbian-stretch-lite" image.

The script output:

```
pi@raspberrypi:~ $ bash resin-wifi-connect-on-raspbian.sh
'resin-io/resin-wifi-connect'
'resin-wifi-connect-on-raspbian': NetworkManager is already installed
'resin-wifi-connect-on-raspbian': NetworkManager is already active
'resin-wifi-connect-on-raspbian': Retrieving latest release from https://api.github.com/repos/'resin-io/resin-wifi-connect'/releases/latest...
'resin-wifi-connect-on-raspbian': Downloading and extracting ...
'resin-wifi-connect-on-raspbian': command failed: curl -Ls

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
resin-wifi-connect-on-raspbian.sh: line 187: ./resin-wifi-connect: No such file or directory
'resin-wifi-connect-on-raspbian': command failed: ./resin-wifi-connect --version
'resin-wifi-connect-on-raspbian': Successfully downloaded
'resin-wifi-connect-on-raspbian': Run './resin-wifi-connect --help' for available options
```

The `./resin-wifi-connect` binary has not been downloaded.

The issue seems to be the `_arch_url` [is not being set here](https://github.com/resin-io/resin-wifi-connect/pull/117/commits/c712f20f563ac89d4249dfe3414be7ce2c7b71e6#diff-4187df257a7790358df255900bc421c1R156) as it's not logged:

`'resin-wifi-connect-on-raspbian': Downloading and extracting ...`

Weirdly, if I remove the single quote marks around the [following line](https://github.com/resin-io/resin-wifi-connect/pull/117/commits/c712f20f563ac89d4249dfe3414be7ce2c7b71e6#diff-4187df257a7790358df255900bc421c1R7).

From this:
    `: "${RWC_REPO:='resin-io/resin-wifi-connect'}"`

To this:
    `: "${RWC_REPO:=resin-io/resin-wifi-connect}"`

Then it works correctly.

Correct log output:

```
pi@raspberrypi:~ $ sudo bash resin-wifi-connect-on-raspbian.sh
resin-io/resin-wifi-connect
'resin-wifi-connect-on-raspbian': NetworkManager is already installed
'resin-wifi-connect-on-raspbian': NetworkManager is already active
'resin-wifi-connect-on-raspbian': Retrieving latest release from https://api.github.com/repos/resin-io/resin-wifi-connect/releases/latest...
'resin-wifi-connect-on-raspbian': Downloading and extracting https://github.com/resin-io/resin-wifi-connect/releases/download/v3.0.0/resin-wifi-connect-v3.0.0-linux-rpi.tar.gz...
./
./resin-wifi-connect
./public/
./public/js/
./public/js/bootstrap.min.js
./public/js/jquery.min.js
./public/js/index.js
./public/img/
./public/img/logo.svg
./public/img/favicon.png
./public/index.html
./public/css/
./public/css/bootstrap.min.css
'resin-wifi-connect-on-raspbian': Successfully downloaded resin-wifi-connect 3.0.0
'resin-wifi-connect-on-raspbian': Run './resin-wifi-connect --help' for available options
```

**Comment by majorz** [comment]
Thanks for reporting this. I will fix it today and merge with master. Additionally I need to fix the error handling part, since `exit` does not exit the process from a subshell.

**Comment by andrewn** [comment]
Let me know if you'd like me to retest.

Thanks for all the work on the new version, it's great!

**Comment by majorz** [comment]
@andrewn, hi Andrew, the Raspbian install script will be merged today. You may give it a go whenever you have available time for that.

I fixed the above error and the error handling as well.

Additionally I made the application to be installed to `/usr/local/sbin` and the UI web assets to be placed into `/usr/local/share/wifi-connect/ui`. It will be on the PATH this way after running the script. I needed to make the application compatible with install paths, so this is mainly why it took a bit longer to get the script ready.

Before the merge is done, you may find the script in the respective branch here:
https://github.com/resin-io/resin-wifi-connect/blob/116-raspbian-install-script/scripts/raspbian-install.sh

No uninstallation option is available for now, but I will add that soon.

**Comment by majorz** [comment]
Closing the issue now. Let's open new ones, if other problems are found.

**Comment by andrewn** [comment]
Just tested on a Pi 3 with fresh Raspbian Lite and it works perfectly!

**Comment by majorz** [comment]
Excellent!
