### ISSUE TITLE
Isolated Wi-Fi Network

### ISSUE THREAD

**Issue by rhwood** [resin-io/resin-wifi-connect#151]
I have a scenario where I have a cluster of devices where no external network is available. I would like to be able to use wifi-connect to configure one device to run a Wi-Fi network that the other devices can be connected to (using wifi-connect to point them in the right direction).

(The scenario is a model train show where a modular layout has been created. The first device will allow users to run trains using a web app on their phones on its own password-protected Wi-Fi network. The other devices control accessories on individual modules, but link [once on the same network as the first device] their controls to that first device so the single web app on a phone controls accessories on the layout.)

**Comment by majorz** [comment]
@rhwood I totally forgot to mention in this issue that as of version 4, WiFi Connect does not require the network to have Internet connectivity. It will just output a warning message if so, which can be ignored in your use case. Closing the issue, since we support isolated networks now.

**Comment by nagualcode** [comment]
is it possible to share my ethernet internet connectivity to wifi-connect AP connected clients? Maybe with iptables?
