### ISSUE TITLE
Make input box for passphrase a proper password field

### ISSUE THREAD

**Issue by vpetersson** [resin-io/resin-wifi-connect#160]
I'm not sure if this only affects iOS, but because the input fields for the passphrase is a regular input field, iOS tries to use auto correct on whatever you type. Moreover, it also adds a space after the passphrase.

My guess is that it would be easy to workaround this by simply setting `<input type="password">` on the input box, but I have not validated this.

**Comment by majorz** [comment]
We had internal discussion about refreshing the UI in the near future, but until then what you suggest definitely makes sense and I will make an update tomorrow.

**Comment by majorz** [comment]
This is actually a regression that happened in an older commit due to large amount of replacements. The version before this one was using `type="password"`:

https://github.com/resin-io/resin-wifi-connect/commit/04a5de06a00603d017b773a21e15831f0c3e0be7#diff-528c3923d718a8860f5d8c05c3931c55
