### ISSUE TITLE
Auto connect with all known previous wifi network credentials

### ISSUE THREAD

**Issue by gchanteloube** [resin-io/resin-wifi-connect#162]
Good morning, everyone,

Thank you for this wonderful project! I have a question, does version 3 allow automatic connection on known networks, not just the last one?
If I have set up my device on network A, change my location, set it up again on network B, and come back to network A, I have to set it up again on network A. Is it possible that it keeps network A and all the networks already known?

Thank you very much for your return and congratulations again!
Gui

**Comment by majorz** [comment]
Hi, this is coming in version 4, which is already in a PR awaiting for some final checks: https://github.com/resin-io/resin-wifi-connect/pull/157

**Comment by gchanteloube** [comment]
Great! Thx

**Comment by majorz** [comment]
Version 4 including support for multiple connection profiles is now released.
