### ISSUE TITLE
Exit codes and error-chain error handling

### ISSUE THREAD

**Issue by abrodersen** [resin-io/resin-wifi-connect#166]
[Front Thread](https://app.frontapp.com/open/cnv_im8msx)

User was tripped up by the fact that `wifi-connect` returned a success code when it exited from an error.

**Comment by majorz** [comment]
I am going to convert the error handling to use `error-chain`. The different types of errors can be mapped to different error codes using the `ExitCode` trait that `error-chain` provides.

Related to https://github.com/resin-io-modules/network-manager/issues/109

**Comment by majorz** [comment]
Detailed description in the PR for this issue - #174.
