### ISSUE TITLE
Shorter Raspbian install script URL

### ISSUE THREAD

**Issue by majorz** [resin-io/resin-wifi-connect#168]
Currently our Raspbian install command is a bit long:
`curl https://raw.githubusercontent.com/resin-io/resin-wifi-connect/master/scripts/raspbian-install.sh -sSf | bash`

This can be made 10 chars shorter by adding a redirect option to curl + a more direct URL:
`curl https://github.com/resin-io/resin-wifi-connect/raw/master/scripts/raspbian-install.sh -sSfL | bash`

**Comment by lurch** [comment]
You could also make it _much_ shorter by using a URL-shortening service? (bit.ly, goo.gl, etc.)
Although piping the output of a shortened-URL directly to bash might be considered bad-practice from a security viewpoint. https://curlpipesh.tumblr.com/

@brownjohnf Out of curiosity, would there be any possibility of automatically hosting / mirroring this on resin.io (or one of its subdomains), so the the command above would just be e.g. `curl https:/resin.io/resin-wifi-connect/raspbian-install.sh -sSfL | bash` ? Although I suspect this probably isn't important enough of an issue to warrant spending any time on... unless there are also other circumstances where a similar approach would also be useful? See e.g. https://github.com/resin-io/etcher/issues/1476 (and I'm sure we had an issue where somebody was asking for shorter download URLs for the [Etcher CLI](https://etcher.io/cli/) which currently have URLs like https://github.com/resin-io/etcher/releases/download/v1.3.1/Etcher-cli-1.3.1-linux-x64.tar.gz , but for some reason I can't find that now). Might apply to resin-cli too @pimterry ?

**Comment by majorz** [comment]
Now that you mentioned it, @apostolism purchased http://wificonnect.io/ a couple of months ago. A redirect should do it (there is already an -L argument to curl included) and the URL can become quite short as well: `http://wificonnect.io/raspbian-install.sh`

**Comment by brownjohnf** [comment]
We could set up a redirect there, but I'd rather not mess with it since it doesn't seem worth the effort.

**Comment by majorz** [comment]
Right, this is something for the future eventually if we launch a website. The idea was to use the static generator tool that Craig was working on, but we talked about that once and never continued the conversation.

**Comment by lurch** [comment]
> The idea was to use the static generator tool that Craig was working on

[Landr](https://github.com/resin-io/landr), right? I'm not sure who's taken that on now, but I remember hearing @jviotti talking about it quite enthusiastically :slightly_smiling_face:

**Comment by majorz** [comment]
Yes, Landr it was :)
