### ISSUE TITLE
Trap exit signals and exit gracefully

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-wifi-connect#180]
This will allow users to terminate WiFi Connect and have the device back in client mode cleanly by  stopping the AP and dnsmasq.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_8ec9)

**Comment by majorz** [comment]
I am encountering issues with trapping the signals in a separate thread, so I created a playground repo for investigating this further: https://github.com/resin-io-playground/trap-signals-rs

**Comment by majorz** [comment]
A new thread is spawned for trapping Unix exit signals. The main thread is masked to not receive them, which is inherited by all child threads as well. If Crtl+C is pressed or the application is killed with SIGTERM, the signal handling thread will trap those signals and the application will shutdown gracefully by stopping the access point and exiting the dnsmasq child process.
