### ISSUE TITLE
Error: Creating the captive portal failed.

### ISSUE THREAD

**Issue by edeuxk** [resin-io/resin-wifi-connect#190]
I made a fresh install with the last Raspbian iso file.
It's a Raspberry 3.

<img width="436" alt="screen shot 2018-03-13 at 7 06 23 pm" src="https://user-images.githubusercontent.com/8247995/37379637-b28e76e6-26f1-11e8-9cea-71005723b00b.png">

But I have this error : 
![screen shot 2018-03-13 at 7 00 39 pm](https://user-images.githubusercontent.com/8247995/37379644-bff34d70-26f1-11e8-9d69-7e95b6fb5416.png)

`root@raspberrypi:/home/pi/Desktop# wifi-connect`
`WiFi device: wlan0`
`[wifi_connect::network:WARN] No access points found - giving up...`
`Starting access point...`
`[network_manager::dbus_api:ERROR] org.freedesktop.NetworkManager::AddAndActivateConnection method call failed on /org/freedesktop/NetworkManager`
`Error: Creating the captive portal failed`
  `caused by: D-Bus failure: org.freedesktop.NetworkManager::AddAndActivateConnection method call failed on /org/freedesktop/NetworkManager`
  `caused by: D-Bus failure: Method call failed after 10 retries`
`root@raspberrypi:/home/pi/Desktop#`

What do I have to do to make it work?

**Comment by majorz** [comment]
@edeuxk Thanks for reporting this. Can you please run it as root: `sudo wifi-connect`.

There is an open issue for this - #122, which I am planning to address soon.

**Comment by majorz** [comment]
I addressed it now in #193 and this will be merged soon. Closing it in favor of #122.

**Comment by edeuxk** [comment]
As you can see I was root.

**Comment by majorz** [comment]
I somehow missed that, since it is the same error log as when not running as root. I just did the same as you on top of the just released Raspbian version 2018-03-13 and things are running well. I will pull now an older 2017-11-29 version to confirm how things are working there.

**Comment by edeuxk** [comment]
No worries :)
Thanks for trying to help.

**Comment by majorz** [comment]
I tried now the Raspbian Lite 2017-11-29 version and things worked correctly. I will need to try the Desktop version as well though just in case there are some permission setting differences. I will do that tomorrow and ping you back.

```
Processing triggers for libc-bin (2.24-11+deb9u1) ...
Processing triggers for systemd (232-25+deb9u1) ...
Processing triggers for dbus (1.10.22-0+deb9u1) ...
WiFi Connect Raspbian Installer: Retrieving latest release from https://api.github.com/repos/resin-io/resin-wifi-connect/releases/latest...
WiFi Connect Raspbian Installer: Downloading and extracting https://github.com/resin-io/resin-wifi-connect/releases/download/v4.0.6/wifi-connect-v4.0.6-linux-rpi.tar.gz...
WiFi Connect Raspbian Installer: Successfully installed wifi-connect 4.0.6
WiFi Connect Raspbian Installer: Run 'wifi-connect --help' for available options


root@raspberrypi:~# wifi-connect 
WiFi device: wlan0
Access points: ["blue2.4ghz", "Home_DD", "DOGE", "DAMYAN", "HUAWEI-6R8p", "Hedgehog", "TP-LINK_20DC", "TP-LINK_DE935A", "botev1912", "NIKI"]
Starting access point...
Access point 'WiFi Connect' created
Starting HTTP server on 192.168.42.1:80
```

**Comment by edeuxk** [comment]
So I tried with the Raspbian Lite 2017-11-29 with your command line.
It failed but someone opened an issue.
So I downloaded the install script and make it run.

It worked perfectly.
If you're in SF I'll buy you a coffee 👍

**Comment by majorz** [comment]
Right, this was fixed yesterday as well. Cheers!

**Comment by jbrepogmailcom** [comment]
Hello, may I ask please? Do I understand correctly that this error has been fixed by using different OS? I am on Raspbian Stretch with lots of SW installed and I can not just change OS. What can I do? Getting same error...
