### ISSUE TITLE
Use it on a Node.js application

### ISSUE THREAD

**Issue by diogoperillo** [resin-io/resin-wifi-connect#199]
Hello,
I'm new on resin.io but already loving it!
I'm building a Node.js app for the Raspberry Pi 3 and having the final user connect the device to the internet is essential for my app.

Is it possible to use this project with node js? If so, any suggestion of how to get started?

**Comment by majorz** [comment]
@diogoperillo Hi, somehow I did not see this issue last week.

You usually have to start WiFi Connect before your other application in the container. There is not any problem in using WiFi Connect with a node js application. Please take a look at our example start script for more information on how you could do it: https://github.com/resin-io/resin-wifi-connect/blob/master/scripts/start.sh

The example start script is started by the example Dockerfile: https://github.com/resin-io/resin-wifi-connect/blob/master/Dockerfile.template

Please let me know if you have any questions.

**Comment by majorz** [comment]
Closing the issue as guidelines were provided and no further action is needed for now.
