### ISSUE TITLE
Configurable listening port

### ISSUE THREAD

**Issue by majorz** [resin-io/resin-wifi-connect#203]
Currently the web server behind the captive portal listens on port 80. Add an option for making the listening port configurable.

There will be no rules added to route all the traffic from port 80 to the configured port. That means that a third-party application should listen on port 80:
* reverse proxy that routes the traffic to the specified port
* application that uses the JSON API we provide. It may or may not reuse our UI. Currently our JSON API is unofficial and may change before before we make it so (which will be soon). The [JS file of our UI](https://github.com/resin-io/resin-wifi-connect/blob/master/ui/js/index.js) can be used as a reference.

**Comment by nagualcode** [comment]
if I specify a port, other than 80, the captive portal wont auto load.
