### ISSUE TITLE
Doesn't build with a C++ error in dbus package

### ISSUE THREAD

**Issue by emirotin** [resin-io/resin-wifi-connect#21]
```
  CXX(target) Release/obj.target/dbus/src/object_handler.o
../src/signal.cc: In function ‘void Signal::DispatchSignal(v8::Handle<v8::Value>*)’:
../src/signal.cc:29:83: error: invalid conversion from ‘v8::Handle<v8::Value>*’ to ‘v8::Local<v8::Value>*’ [-fpermissive]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), Nan::New(handler), 6, info);
                                                                                   ^
In file included from ../src/signal.cc:5:0:
../node_modules/nan/nan.h:803:35: note: initializing argument 4 of ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’
   NAN_INLINE v8::Local<v8::Value> MakeCallback(
```

I tried different node version (0.10.x, 0.12.x, latest resin/beaglebone-node), added `libglib2.0-dev` package (mentioned in the dbus' readme), installed newest `node-gyp` with `npm install --unsafe-perm -g node-gyp` — still the same error.

I've noticed that dbus has updated recently to 0.2.13 that uses nan-2.1.0, but its changelog doesn't mention any breaking change that looks applicable.

**Comment by pcarranzav** [comment]
@emirotin could you please check whether this is fixed in ab5c544b3fed9f1375479a6797ec29b105784ba5 ?

**Comment by pcarranzav** [comment]
(I pushed the quick fix and raised the issue in Shouqun/node-dbus#108 - we'll roll back after it's fixed there)

**Comment by emirotin** [comment]
Yes it builds, cheers @pcarranzav!
