### ISSUE TITLE
Wifi Connect for ubuntu

### ISSUE THREAD

**Issue by AvishekHardin** [resin-io/resin-wifi-connect#216]
Hello Team,

thanks for this marvelous work. 

I have a question rather than an issue, do we have similar things for Ubuntu please? if yes, can you please share the link. I tried searching, but was unsuccessful. 

PLease help.
Regards,

**Comment by majorz** [comment]
WiFi Connect should work on Ubuntu as well. Have you tried running it on Ubuntu? I have not done that before, but I do not see a reason it should not work.

**Comment by majorz** [comment]
What device you are running Ubuntu on?

**Comment by AvishekHardin** [comment]
Hello Majorz,

Ubuntu is installed on my laptop its an HP EliteBook 8570p. The wifi on this laptop does support Access Point mode.

**Comment by AvishekHardin** [comment]
Hello Majorz,

Good Morning,
I tried and its working perfectly on Ubuntu, you rock!!.. thanks for your help. this is what i was looking for.

on top of this, how can i compile the provided source for other architecture? e.g ARM.
can you please guide me.

Best Regards,

**Comment by majorz** [comment]
Hi Avishek,

You do not have to compile as we provide precompiled binaries for the different architectures.

For Raspberry Pi 2/3 you may use the archive from the releases page ending with `armv7hf.tar.gz`, for Raspberry Pi 1/Zero you may use the archive ending with `rpi.tar.gz`.

Thanks,
Zahari

**Comment by majorz** [comment]
If you are targeting another ARM device, you will most probably need the `armv7hf.tar.gz` archive.

**Comment by AvishekHardin** [comment]
Well noted, thanks for your help Majorz. 
That's really helpful.

Best Regards,
