### ISSUE TITLE
Reset Wifi Connection

### ISSUE THREAD

**Issue by cchamikara** [resin-io/resin-wifi-connect#218]
I wonder how someone can rest pre configured wifi connection using resin wifi connect, maybe by setting a GPIO pin high for 3 seconds etc..

**Comment by majorz** [comment]
Sorry for the late response - somehow I missed the notification for this issue.

Currently the only way for this is to launch WiFi Connect for a second time and enter credentials for the same network in the same way it was done initially. When new credentials are entered, the old connection profile for the same network will be deleted and new one created. Does that answer your question?
