### ISSUE TITLE
No Access Points Found 

### ISSUE THREAD

**Issue by cSchubes** [resin-io/resin-wifi-connect#223]
Hi,

Occasionally, the program will report that is unable to find any access points. The issue is sporadic, however simply restarting the binary does not solve it. Once this error happens, the only way to get the NetworkManager to successfully find access points is to power cycle the whole device. This makes me think it is an issue with how the program interacts with the NetworkManager.

I am using a BeagleBone Green Wifi running resinOS 2.12. Any ideas on why this may happen? It's causing me a great deal of annoyance.

**Comment by majorz** [comment]
Does the issue occur when the device is already connected to a WiFi network? Also can you please try restarting NetworkManager to see whether this helps?

**Comment by cSchubes** [comment]
The issue occurs when no WiFi network is connected. Restarting the NetworkManager with `systemctl restart NetworkManager` seems to fix it, though I am curious how it happens in the first place. Regardless, how can I restart NetworkManager from the container? What environment variable will I need to expose?

**Comment by majorz** [comment]
Thanks, this clarifies our findings in #206. The solution is to integrate the check for empty access point list and restarting NetworkManager if needed in WiFi Connect. I will close this issue in favor of the other issue. I will fix it soon.
