### ISSUE TITLE
ADD: Artik aarch64 support

### ISSUE THREAD

**Issue by andrewjaykeller** [resin-io/resin-wifi-connect#227]
Hello Resin Team!

I was wondering if you could add support for Artik 710?

When I try to build with the example with this library, I get errors:

```bash
The command '/bin/sh -c curl https://api.github.com/repos/resin-io/resin-wifi-connect/releases/latest -s     | grep -hoP 'browser_download_url": "\K.*aarch64\.tar\.gz'     | xargs -n1 curl -Ls     | tar -xvz -C /usr/src/app/' returned a non-zero code: 2
```

Thanks so much for your time and energy!

AJ 😄

**Comment by majorz** [comment]
Hi AJ,

I run the above command on my laptop and it downloads the aarch64 archive properly. Does the `/usr/src/app/` folder exists in the container before running the command? In our example Dockerfile the `WORKDIR /usr/src/app` is before the wifi-connect download.

In any way, aarch64 binaries are provided with our releases.

Alternatively you may use:
```
curl -Ls https://github.com/resin-io/resin-wifi-connect/releases/download/v4.2.0/wifi-connect-v4.2.0-linux-aarch64.tar.gz  | tar -xvz -C /usr/src/app/
```

Please let me know how that works for you.

**Comment by majorz** [comment]
Closing this one as we provide aarch64 binaries.
