### ISSUE TITLE
Change wifi problem at Rasbian

### ISSUE THREAD

**Issue by leejaeuk** [resin-io/resin-wifi-connect#232]
hello, admin.
i have problem about re-connection wifi. (Current status connect wifi)
First execution work very well ( sudo wifi-connect and setup my mobile phone from captive portal)

After Wifi connection, i want to change another wifi. then i execute same command( sudo wifi-connect) but existing wifi is disconneted with this error printed like this.

"Error : Cannot start HTTP server on '192.168.42.1:80':address not available
"dnsmasq : unknown interface wlan0"

i check the dnsmasq status but it activated well.

give me some help.
thank you.

**Comment by leejaeuk** [comment]
@majorz  :(

**Comment by majorz** [comment]
Hi @leejaeuk, I did not had a chance to check this earlier. Just tried that out and it works well for me here. What particular RPi device type are you using? And also which Raspbian version are you running it on?

**Comment by leejaeuk** [comment]
@majorz 
Hi, I'm using raspberry pi 3B+, 3B and zero.
and using raspbian OS  version is contemporary version. 

relate this problem..
i found a kind of solution. 

first, i delete wifi connected information file that was wifi name, when i connected.   [ cd /etc/NetworkServicemanager/system..(i don'y remember exactly name of directory)]

and i execute  ' sudo systemctl stop dnsmasq ' 

then, i can success changed to another wifi.

without this process( i just executed 'wifi-connect'), wifi change have problem.

**Comment by majorz** [comment]
I am glad that you found a solution for this. So this is an issue with administering the Raspbian installation and not directly connected to WiFi Connect, so I am closing this issue as successfully resolved.

**Comment by andrewjaykeller** [comment]
Was a better work around ever found for this issue?

```
./wifi-connect --portal-listening-port 45454
WiFi device: wlan0
[wifi_connect::network:WARN] No access points found - giving up...
Starting access point...
Access point ‘WiFi Connect’ created
Starting HTTP server on 192.168.42.1:45454
Error: Cannot start HTTP server on ‘192.168.42.1:45454’: address not available
root@111e10d:/usr/src/app#
dnsmasq: unknown interface wlan0
```

**Comment by majorz** [comment]
@andrewjaykeller it looks like the wifi driver is crashing or something similar - first it is not able to detect networks, and then it is not reachable by dnsmasq. Is this for the Artik board from the previous ticket? I looked that up and I noticed that it uses the proprietary Marvell WiFi driver, which is not being kept up to date in the Samsung Linux kernel tree. What is more worrying is that there are not any kernel updates from a long time ago: https://github.com/SamsungARTIK/linux-artik.

What I really suggest is trying to run WiFi Connect on different OS systems - the one that Samsung Artik officially supports (I think they had Ubuntu download), and also latest Resin OS. If you get it working on Ubuntu, but not on balenaOS, then it should not be hard for my team mates to fix this. If it is not working on the official Artik distro, maybe you need to take a look at a different board, as their kernel tree looks a bit abandoned.

**Comment by andrewjaykeller** [comment]
@alexcastillo see above

**Comment by andrewjaykeller** [comment]
@majorz I'm trying to test wifi connect on the base ubuntu image and getting error:

```bash
[root@artik ~]# curl -SLO "https://github.com/balena-io/wifi-connect/releases/download/v4.2.2/wifi-connect-v4.2.2-linux-armv7hf.tar.gz"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   630    0   630    0     0    422      0 --:--:--  0:00:01 --:--:--   422
100 1409k  100 1409k    0     0   484k      0  0:00:02  0:00:02 --:--:-- 1432k
[root@artik ~]# tar -xzf wifi-connect-v4.2.2-linux-armv7hf.tar.gz
[root@artik ~]# ls
ui  wifi-connect  wifi-connect-v4.2.2-linux-armv7hf.tar.gz
[root@artik ~]# cd wifi-connect
-bash: cd: wifi-connect: Not a directory
[root@artik ~]# ;s
-bash: syntax error near unexpected token `;'
[root@artik ~]# ./wifi-connect
Cannot get the NetworkManager service state
[network_manager::dbus_api:ERROR] org.freedesktop.NetworkManager.Settings::ListConnections method call failed on /org/freedesktop/NetworkManager/Settings
Error: Deleting access point connection profile failed
  caused by: D-Bus failure: org.freedesktop.NetworkManager.Settings::ListConnections method call failed on /org/freedesktop/NetworkManager/Settings
  caused by: "The name org.freedesktop.NetworkManager was not provided by any .service files"
[root@artik ~]# export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
[root@artik ~]# ./wifi-connect                                                  Cannot get the NetworkManager service state
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: D-Bus error: Failed to connect to socket /host/run/dbus/system_bus_socket: No such file or directory (org.freedesktop.DBus.Error.FileNotFound)', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
[root@artik ~]# 
```

**Comment by andrewjaykeller** [comment]
@majorz What is the proper dbus location when not running inside a container

**Comment by andrewjaykeller** [comment]
I solved a lot of my issues and was able to *SEE ALL THE WIFI NETWORKS!!!!!*

```bash
NetworkManager service started successfully
[ 1519.475000] stmmac_hw_setup: DMA engine initialization failed
[ 1519.480000] stmmac_open: Hw setup failed
[ 1519.705000] stmmac_hw_setup: DMA engine initialization failed
[ 1519.710000] stmmac_open: Hw setup failed
[ 1519.850000] stmmac_hw_setup: DMA engine initialization failed
[ 1519.855000] stmmac_open: Hw setup failed
WiFi device: wlan0
[ 1519.995000] stmmac_hw_setup: DMA engine initialization failed
[ 1520.000000] stmmac_open: Hw setup failed
[ 1520.140000] stmmac_hw_setup: DMA engine initialization failed
[ 1520.145000] stmmac_open: Hw setup failed
Access points: ["ACME", "PFPREPORTING", "GreenDesk", "PFPREPORTING", "", "DVR", "WLoFT", "", "WLoFT", "GreenDesk", "GreenDesk", "WLoFT", "DVR", "", "Radio Test", "bananaa", "DVR", "WiFi Connect", "DVR", "uequalsu", "GreenDesk", "WLoFT", "", "", "WMS", "DIRECT-E9-HP OfficeJet 3830", "DVR", "Radio Test", "uequalsu_5G", "DIRECT-66-HP M252 LaserJet", "GreenDesk", "", "WLoFT", "DIRECT-C1-HP ENVY 7640 series", "DVR", "seretstudios", "GreenDesk", "WLoFT", "GreenDesk", "WLoFT", "", "DVR", "WLoFT", "", "", "WMS", "DVR", "GreenDesk", "GreenDesk", "DVR", "DIRECT-ba-HP M477 LaserJet", "WLoFT", "", "GreenDesk", "DIRECT-57-HP OfficeJet Pro 7740", "DVR", "DVR", "", "GreenDesk", "", "WLoFT", "GreenDesk", "", "GreenDesk", "WLoFT", "GreenDesk", "DVR", "WLoFT", "DVR", "BEAM", "", "GreenDesk", "", "GreenDesk", "WLoFT", "DVR", "DVR", "GreenDesk", "", "WLoFT", "DVR", "", "WLoFT", "", "GreenDesk", "", "DVR", "GreenDesk", "DVR", "GreenDesk", "WLoFT", "", "DVR", "WLoFT", "", "GreenDesk"]
Starting access point...
Access point 'WiFi Connect' created
Starting HTTP server on 192.168.42.1:80

dnsmasq: failed to create listening socket for 192.168.42.1: Address already in use

```

**Comment by mowi22** [comment]
I'm getting this same error. Any update?
