### ISSUE TITLE
Wifi dongle wu710n

### ISSUE THREAD

**Issue by samouds** [resin-io/resin-wifi-connect#24]
Hello,

Is the Wifi dongle wu710n will work for the hotspot mode ? because I'm getting Cannot read property '0' of undefined too.

Thanks.

**Comment by pcarranzav** [comment]
Hi @samouds - As far as I see, that dongle has a Realtek RTL8188CU chipset, so it is not supported, sorry. Please use a dongle with an Atheros or Ralink chipset, ideally one from the [list in the README](https://github.com/resin-io/resin-wifi-connect#supported-boards--dongles).
Cheers!
