### ISSUE TITLE
No Retry On Authentication After Entering Password. 

### ISSUE THREAD

**Issue by TexasWormHole** [resin-io/resin-wifi-connect#25]
After entering as password in the captive portal, it seems that there is only one try to associate. If there is a comms error like a 3=DEAUTH_LEAVING rather than a password error it still restarts the AP.  A retry would have connected.

The 'Trying to join known networks' path does have 3 retries and will connect in that particular case.
I have seen the NUC wifi take a bit of time to settle down when any of its modes have changed.

-Andy

**Comment by pcarranzav** [comment]
Thanks for reporting. I'll be adding extra retries soon, will PR when ready.
