### ISSUE TITLE
Confirm ISC license

### ISSUE THREAD

**Issue by andrewn** [resin-io/resin-wifi-connect#30]
Thanks for creating such a great tool. I'd love to use it in my own projects but just want to double-check the license. 

The [package.json specifies ISC](https://github.com/resin-io/resin-wifi-connect/blob/master/package.json#L11), is that correct?

**Comment by emirotin** [comment]
Hi. The permission should be permissive though we may reconsider it to be Apache instead of ISC. We'll add another comment here as soon as we update it (or decide to keep ISC).

**Comment by pcarranzav** [comment]
@andrewn - as @emirotin commented, it's Apache 2. Fixed now, sorry for the confusion.
