### ISSUE TITLE
Installation fails on node v5.10.0

### ISSUE THREAD

**Issue by andrewn** [resin-io/resin-wifi-connect#34]
I'm trying to get `wifi-connect` running standalone on a Raspberry Pi using nodejs v5.10.0. It successfully runs on node 0.10.

Installation fails because further down the dependency chain something relies on `dbus@0.2.12` which I don't think supports newer versions of node.

The latest version of dbus (0.2.17) installs without errors.

I can't find the repos for `connman-simplified-resin` and `connman-api-resin` to raise pull requests to update their dependencies.

```
resin-wifi-connect@1.0.0 
└─┬ connman-simplified-resin@0.1.5 
  └─┬ connman-api-resin@0.3.3 
    ├── async@0.2.10 
    └─┬ dbus@0.2.12 
      └── nan@1.9.0 
```

**Comment by pcarranzav** [comment]
Hi @andrewn - cool that you're doing this!
Yeah, those packages are just local builds I did so that wifi-connect kept working while the fix for [this](https://github.com/Shouqun/node-dbus/issues/108) got propagated in the dependencies - and then I forgot to switch back to the official connman-simplified and connman-api packages.  I'll do that now that they seem to be working well.

**Comment by andrewn** [comment]
Ah, that makes sense. Switching back to the latest dependencies works really well.

For what it's worth, [here are the scripts](https://github.com/radiodan/provision/tree/minimal/steps/wifi-connect) I'm running to get `wifi-connect` running on a Pi with Jessie. I had to compile my own `connman` with your patches to allow passwordless tethering.

Thanks for wifi-connect!

**Comment by pcarranzav** [comment]
Cool! Radiodan looks very interesting. I'm curious on why you don't want to use resin for it though :P, would love to chat if you wanna say hi on [gitter](https://gitter.im/resin-io/chat) or via email (hello@resin.io)

**Comment by dovy** [comment]
@pcarranzav this hasn't been pushed to the RPi 3 rebase branch.  :P

**Comment by petrosagg** [comment]
project updated to node v6.3 and dropped `connman-simplified-resin` from dependencies
