### ISSUE TITLE
AP OK but not the captive portal

### ISSUE THREAD

**Issue by samouds** [resin-io/resin-wifi-connect#36]
Hello,

I'm trying to create a AP with my Rpi2, everything is working well : I can see the AP in my wifi list and connect to it. But the captive portal won't open automatically. 

I need to type the ip address in the browser to see the captive portal. By the way the Rpi2 internal IP 192.168.5.1 (dynamic) is different from 192.168.0.1 (which we have in the db.catchall file)

how the captive portal can be open after the connection to the AP ? 
Do I need to change the db.catchall to update the IP after each reboot ?

any clue ?

**Comment by pcarranzav** [comment]
(as mentioned on gitter)
Hi @samouds - looks like something might be going wrong with the DNS server. The IP in db.catchall shouldn't affect much since we're also using iptables rules to forward the packets.
Could you check (with `ps -Af` on a terminal) whether the DNS is running? And check if the iptables rules are in place? (`iptables -t nat -L`)
(with the AP running)

**Comment by curcuz** [comment]
related to #33

**Comment by danielbh** [comment]
@pcarranzav 

I have same problem. Output of ps

UID        PID  PPID  C STIME TTY          TIME CMD                                                                                                
root         1     0  0 12:22 ?        00:00:01 /bin/sh -c ./start                                                                                 
root        22     1  0 12:22 ?        00:00:00 udevd                                                                                              
root        25     1  0 12:22 ?        00:00:00 /bin/bash ./start                                                                                  
root        26    25  1 12:22 ?        00:00:04 npm                                                                                                
root        58    26  0 12:22 ?        00:00:00 sh -c cd src && node app.js                                                                        
root        59    58  1 12:22 ?        00:00:05 node app.js                                                                                        
root        83     1  0 12:22 ?        00:00:00 hostapd -B wlan0-hostapd.conf                                                                      
root        90     1  0 12:22 ?        00:00:00 udhcpd wlan0-udhcpd.conf                                                                           
root        92    59  0 12:22 ?        00:00:00 named -f                                                                                           
root       108     0  0 12:28 ?        00:00:00 /bin/bash                                                                                          
root       131   108  0 12:28 ?        00:00:00 ps -Af   

output of iptables

Chain PREROUTING (policy ACCEPT)                                                                                                                   
target     prot opt source               destination                                                                                               
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL                                                        
TETHER     all  --  anywhere             anywhere                                                                                                  
                                                                                                                                                   
Chain INPUT (policy ACCEPT)                                                                                                                        
target     prot opt source               destination                                                                                               
                                                                                                                                                   
Chain OUTPUT (policy ACCEPT)                                                                                                                       
target     prot opt source               destination                                                                                               
DOCKER     all  --  anywhere            !loopback/8           ADDRTYPE match dst-type LOCAL                                                        
                                                                                                                                                   
Chain POSTROUTING (policy ACCEPT)                                                                                                                  
target     prot opt source               destination                                                                                               
MASQUERADE  all  --  172.17.0.0/16        anywhere                                                                                                 
                                                                                                                                                   
Chain DOCKER (2 references)                                                                                                                        
target     prot opt source               destination                                                                                               
RETURN     all  --  anywhere             anywhere                                                                                                  
                                                                                                                                                   
Chain TETHER (1 references)                                                                                                                        
target     prot opt source               destination                                                                                               
DNAT       tcp  --  anywhere             anywhere             tcp dpt:http to:192.168.42.1:8080                                                    
DNAT       tcp  --  anywhere             anywhere             tcp dpt:https to:192.168.42.1:8080                                                   
DNAT       udp  --  anywhere             anywhere             udp dpt:domain to:192.168.42.1:53

**Comment by danielbh** [comment]
Also I should not im running rpi3-rebased branch.

**Comment by danielbh** [comment]
Forgetting AP seems to fix this. I wonder why?

**Comment by petrosagg** [comment]
resin-wifi-connect is no longer based on iptables. Please re-open if you still have the issue
