### ISSUE TITLE
sometimes scan doesn't retrieve all the available SSIDs

### ISSUE THREAD

**Issue by curcuz** [resin-io/resin-wifi-connect#42]
this seems to result in the AP/Captive procedure to be started even if the device is in proximity of a known network.

**Comment by danielbh** [comment]
+1 :)

**Comment by danielbh** [comment]
Ok so here is some diagnostic data from connmanctl... It looks like maybe permissions are getting changed somewhere.

![screen shot 2016-07-19 at 3 18 13 pm](https://cloud.githubusercontent.com/assets/6653234/16956795/1572785e-4dda-11e6-8bc3-b6b56430d88c.png)

**Comment by danielbh** [comment]
check out this link...  http://connman.connman.narkive.com/iZQ2G54G/wifi-scan-error

**Comment by danielbh** [comment]
sorry this link is better maybe... https://wiki.archlinux.org/index.php/Connman#Error_.2Fnet.2Fconnman.2Ftechnology.2Fwifi:_Not_supported

**Comment by danielbh** [comment]
Here is soething else. The user for dbus-daemon is message+ instead of root. that seems wrong?

![screen shot 2016-07-19 at 8 37 29 pm](https://cloud.githubusercontent.com/assets/6653234/16962160/c3aff412-4df0-11e6-86f6-edfe1679ff1a.png)

**Comment by danielbh** [comment]
the above could have been because I restarted it in terminal with resin.io

**Comment by danielbh** [comment]
Two more observations: 
1) When there is only one configuration in the connections.json array it doesn't work. 
2) I tried doing a timeout before app reboots in the hope that connman was getting cut off before finishing what it had to do. Didn't work.
