### ISSUE TITLE
start script pattern prevents recovery if target wifi AP no longer available

### ISSUE THREAD

**Issue by BrianAdams** [resin-io/resin-wifi-connect#46]
https://github.com/resin-io/resin-wifi-connect/commit/449eb2a55b80f0d6c90f2f2267fcaa8f1c7e3833#diff-ea2b2676c28c0db26d39331a336c6b92

It now simply skips running wifi-connect if an existing configuration has been cached in /data.  But if that wifi access point is no longer available, wifi-connect is never run such that you can recover and put in the new wifi details.

**Comment by petrosagg** [comment]
The rationale behind this change is that the application should have the logic to determine if a re-configuration should be done or not. If you restart your router you don't want a device to suddenly enter AP mode. Or you may want to trigger AP mode when your user pushes a reset button.

Point being, the logic for this should be handled by the application.

**Comment by petrosagg** [comment]
I updated the documentation to reflect this

**Comment by danielbh** [comment]
Yeah it's too hard to deal with. Like if for example there is a power failure you want the device to go back into normal operations. Not be trapped in AP mode.
