### ISSUE TITLE
blog entry talks about connectionsFromFile, can't find that in the code

### ISSUE THREAD

**Issue by alberttwong** [resin-io/resin-wifi-connect#75]
blog entry at https://resin.io/blog/resin-wifi-connect/ talks about connectionsFromFile, can't find that in the code.  thinking it could help https://github.com/resin-io/resin-wifi-connect/issues/74

**Comment by josephroberts** [comment]
Hi @alberttwong 

`resin-wifi-connect` has moved on a fair bit since that blog post was written, you can find the updated blog [here](https://resin.io/blog/wifi-wifi-everywhere/)

Currently we don't support multiple connections but that is coming in a new version soon!

I hope that helps
