### ISSUE TITLE
the image already has the correct wifi settings but it still went to captive portal 

### ISSUE THREAD

**Issue by alberttwong** [resin-io/resin-wifi-connect#76]
The resin image already has the correct wifi settings.   My expectation from reading the readme and blog entry that it would use that setting and if it couldn't, then it would launch the captive portal.  It seemed that it launched the captive portal regardless. 

related to https://github.com/resin-io/resin-wifi-connect/issues/74

**Comment by josephroberts** [comment]
Hi @alberttwong 

It is correct that `resin-wifi-connect` will always run and start the captive portal if it has not already been configured. 

You can achieve the behavior you require by wrapping `resin-wifi-connect` in your own script, replacing the start script with the below:

```
#!/bin/bash

export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

# Look for the network for a while
GOTNET=0
for ((i=0; i<60; i++))
do
    if curl --output /dev/null --silent --head --fail http://www.google.com; then
        GOTNET=1
        break
    fi
    sleep 1
done

# If no network, start resin-wifi-connect
if [ "$GOTNET" -eq 0 ]; then
    node src/app.js --clear=false
fi

while true; do
    echo "App started"
    sleep 1
done
```
