### ISSUE TITLE
Implement exit codes

### ISSUE THREAD

**Issue by kipe** [resin-io/resin-wifi-connect#80]
If I'm looking at the code correctly, `app.coffee` uses the same exit method regardless if the wifi was connected or not.
The behaviour could be better determined by an external script (implementing the required behaviour for each specific use-case) by using exit codes to determine what caused the program to exit in the first place.

I would suggest implementing the following exit codes (if possible to determine of course):

- 0 - connected to wifi
- 1 - general error
- 2 - argument or configuration variable missing or incorrect
- 10 - credentials set via AP, restarting to try a connection
- 11 - credential set, but failed to connect to the wifi

These codes (try) to follow my understanding of [Exit Codes With Special Meanings](http://www.tldp.org/LDP/abs/html/exitcodes.html).

**Comment by majorz** [comment]
Closing in favor of #166.
