### ISSUE TITLE
Wrong NM_CONNECTIVITY numbers ?

### ISSUE THREAD

**Issue by benoitguigal** [resin-io/resin-wifi-connect#84]
[https://developer.gnome.org/NetworkManager/stable/nm-dbus-types.html#NMConnectivityState](https://developer.gnome.org/NetworkManager/stable/nm-dbus-types.html#NMConnectivityState) 
The documentation specifies 
```
NM_CONNECTIVITY_LIMITED = 3
NM_CONNECTIVITY_FULL = 4
```

but in `networkManger.coffee` we have
```
NM_CONNECTIVITY_LIMITED = 4
NM_CONNECTIVITY_FULL = 5
```

**Comment by josephroberts** [comment]
Good spot. The issue was caused by [this](https://bugzilla.gnome.org/show_bug.cgi?id=776848) bug in the documentation. I will fix the numbering now.
