### ISSUE TITLE
Super simple rust binary 

### ISSUE THREAD

**Issue by josephroberts** [resin-io/resin-wifi-connect#87]
Create a simple rust binary that follows the flowchart below and makes use of the [network_manager](https://github.com/resin-io-modules/network_manager) module we have written. The idea is that users can wrap this binary in their own code to get the various behaviors they need.

![screenshot_2017-04-05_14-13-29_ 0100](https://cloud.githubusercontent.com/assets/1107385/25431463/9008b940-2a78-11e7-9c98-48d3aa0a6696.png)

**Comment by majorz** [comment]
Closing in favor of #104.
