### ISSUE TITLE
Doesn't seem to work on Intel NUC.

### ISSUE THREAD

**Issue by zvin** [resin-io/resin-wifi-connect#96]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1o5j)
https://forums.resin.io/t/does-intel-nuc-wifi-chip-works-with-resin-wifi-connect/957/3

**Comment by josephroberts** [comment]
Connects to https://github.com/resin-os/meta-resin/issues/671

**Comment by josephroberts** [comment]
We need to document the env vars specified in the [config](https://github.com/resin-io/resin-wifi-connect/blob/master/src/config.coffee). Specifically for `iface` for this issue
