### ISSUE TITLE
Doesn't work on edison with resinOS 2.0.5

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-wifi-connect#97]
Tested the `master` branch on the latest resinOS 2.0.5 edison release.
resin-wifi-connect sets up the AP correctly and shows a list of scanned Access points, I entered the correct credentials, but the device never gets connected to the network. 

It seems that the modprobe to reload the firmware fails or something like that, since when i looked into the device on serial, `ifconfig` didn't list `wlan0` anymore.

**Comment by majorz** [comment]
Closing this one, since the latest Edison kernel has better driver support and we no longer do modprobing.
