### ISSUE TITLE
 Error: No introspectable

### ISSUE THREAD

**Issue by pcriadoperez** [resin-io/resin-wifi-connect#99]
Hi,

I am getting this error when flashing a Pi Zero W:
Clear is disabled
11.06.17 18:44:02 (-0400) Device type is raspberry-pi
11.06.17 18:44:02 (-0400) { Error: No introspectable
11.06.17 18:44:02 (-0400)     at /usr/src/app/resin-wifi-connect/node_modules/dbus/lib/bus.js:101:15
11.06.17 18:44:02 (-0400)   cause:
11.06.17 18:44:02 (-0400)    Error: No introspectable
11.06.17 18:44:02 (-0400)        at /usr/src/app/resin-wifi-connect/node_modules/dbus/lib/bus.js:101:15,
11.06.17 18:44:02 (-0400)   isOperational: true }
11.06.17 18:44:02 (-0400) Exiting

If I start from the terminal it works ( $node src/app.js --clear=true )

**Comment by pcriadoperez** [comment]
It works if I increase the sleep time to from 1 to 30
And  set --clear=true

**Comment by majorz** [comment]
We added support for `START_SLEEP` environment variable to the start script in v2.0.8 as a short term solution. The error does not exist in the ongoing rewrite of the application in the Rust language.
